version: '3'

services:
  db:
    container_name: postgresql
    image: postgres:17
    volumes:
      - /c/projects/dv-idico-api/postgres/data
    ports:
      - 7894:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dbdv
    restart: always

  redis:
    container_name: redis
    image: redis:6.2-alpine
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    restart: always

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    restart: always

  dv-idico-api:
    build: .
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    depends_on:
      - db
      - redis
      - minio
volumes:
  postgres-data:
